### ISSUE TITLE
Fix security issues by updating packages

### ISSUE THREAD

**Issue by mlenik** [vacuumlabs/fine-tracker#195]
Check Security page

**Comment by domiin50** [comment]
The other security issues are caused by our internal package [webpack-config-vacuumlabs](https://github.com/vacuumlabs/webpack-config-vacuumlabs). Some dependencies of this package are labeled as severity.
Until the vacuumlabs/webpack-config-vacuumlabs#13 issue won't be resolved and a new version of the package published, it is unable to remove the remaining security alerts.

**Comment by jakuub** [comment]
All security alerts are closed/dismissed
