### ISSUE TITLE
Help dialog on ?

### ISSUE THREAD

**Issue by mikx98** [vacuumlabs/fine-tracker#33]
Show either converted spec or some key shortcuts.

**Comment by jakuub** [comment]
I will reopen this, because I reallized, that each time, I don't remember the shortcut for something, I subcontiosly press `?`. 
I think, that for easy start, it will be necessary to have this functional, fore users to be able to show help really easily from keyboard, and also close easy from keyboard (Esc). 

I also leave this in 1.0 milestone, because I think, it should be there when we show it to colegues.

**Comment by jakuub** [comment]
Autogeneration from spec is ideal scenario. For the launch, I think we don't have to autogenerate them from spec, they can be "hardcoded" into the codebase, and we can leave autogeneration for next task.

I created task for that: #103

**Comment by jakuub** [comment]
Autogeneration is less important then the rest of the 1.0 issues :-)
